# Generated by Django 3.0.1 on 2020-01-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
