# Generated by Django 3.0.1 on 2020-02-11 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='id_no',
            new_name='idno',
        ),
    ]
