# Generated by Django 3.0.1 on 2020-02-07 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.IntegerField(blank=True, null=True)),
                ('maths', models.IntegerField(blank=True, null=True)),
                ('physics', models.IntegerField(blank=True, null=True)),
                ('chemistry', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id_no', models.AutoField(primary_key=True, serialize=False)),
                ('subjectname', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Subject')),
            ],
        ),
    ]
