# Generated by Django 3.0.1 on 2020-01-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200108_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='city',
        ),
    ]
