# Generated by Django 3.0.1 on 2020-02-11 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200211_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='idno',
            new_name='id_no',
        ),
    ]
