# Generated by Django 3.0.1 on 2020-01-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentinfo_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
    ]
