# Generated by Django 3.0.1 on 2020-01-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_studentinfo_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='addmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(blank=True, max_length=20, null=True)),
                ('firstname', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, max_length=20, null=True)),
                ('dateofexam', models.DateField(blank=True, max_length=30, null=True)),
                ('maths', models.CharField(blank=True, max_length=20, null=True)),
                ('physics', models.CharField(blank=True, max_length=20, null=True)),
                ('chemistry', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
