# Generated by Django 3.0.1 on 2020-01-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_addmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmarks',
            name='chemistry',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='addmarks',
            name='id_no',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='addmarks',
            name='maths',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='addmarks',
            name='physics',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
