# Generated by Django 3.0.1 on 2020-01-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200110_0931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addmarks',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='password',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='chemistry',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='dateofexam',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='id_no',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='maths',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='physics',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
