# Generated by Django 3.0.1 on 2020-01-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200110_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='addmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.IntegerField(blank=True, max_length=20, null=True)),
                ('firstname', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, max_length=20, null=True)),
                ('dateofexam', models.DateField(blank=True, max_length=30, null=True)),
                ('maths', models.IntegerField(blank=True, null=True)),
                ('physics', models.IntegerField(blank=True, null=True)),
                ('chemistry', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='chemistry',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='dateofexam',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='id_no',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='maths',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='physics',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='dob',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
