# Generated by Django 3.0.1 on 2020-01-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200110_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmarks',
            name='id_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
