# Generated by Django 3.0.1 on 2020-01-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200108_0944'),
        ('student', '0008_auto_20200110_1011'),
    ]

    operations = [
    ]
